/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 apartment.gltf 
Author: jimbogies (https://sketchfab.com/jimbogies)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-or-apartment-building-6d4dbce51f3b45aea5e165a91c0264ae
Title: Office or Apartment Building
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/apartment.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <lineSegments geometry={nodes.Material2.geometry} material={materials.edge_color000255} />
        <lineSegments geometry={nodes.Material2_7.geometry} material={materials.edge_color128128128255} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.Color01} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials.Color01} />
        <mesh geometry={nodes.Material2_3.geometry} material={materials.Building01_Diffuse} />
        <mesh geometry={nodes.Material2_4.geometry} material={materials.Building02_Diffuse} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials.Roof_Diffuse} />
        <mesh geometry={nodes.Material2_6.geometry} material={materials.Color02} />
      </group>
    </group>
  )
}

useGLTF.preload('/apartment.gltf')
