/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 earth2.gltf --transform 
Files: earth2.gltf [15.61MB] > earth2-transformed.glb [326.18KB] (98%)
Author: Alan Zimmerman (https://sketchfab.com/nenjo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-8a3f6e66955e41d48762d75725d3ab52
Title: Earth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/earth2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Earth_Surfacemat_0.geometry} material={materials['Surface.mat']} scale={100} />
    </group>
  )
}

useGLTF.preload('/earth2-transformed.glb')
